exec_once:
 execs:
  Install Gitlab Runner:
   name: Install Gitlab Runner
   timeout: "2000"
   command: |
     #!/usr/bin/env bash
     wget -O /usr/local/bin/gitlab-runner https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
     sudo chmod +x /usr/local/bin/gitlab-runner
     sudo useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
     sudo gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
     sudo gitlab-runner start
